//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparişOtomasyon.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hedef
    {
        public int ID { get; set; }
        public string Unvan { get; set; }
        public string AdresAdı { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Tanımla { get; set; }
        public string AdresID { get; set; }
    }
}
