//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparişOtomasyon.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSiparisOtomasyonEntities6 : DbContext
    {
        public DbSiparisOtomasyonEntities6()
            : base("name=DbSiparisOtomasyonEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblEslesmelerle> TblEslesmelerle { get; set; }
        public virtual DbSet<TblGezer> TblGezer { get; set; }
        public virtual DbSet<TblGezerProjeler> TblGezerProjeler { get; set; }
        public virtual DbSet<Hedef> Hedef { get; set; }
    }
}
