//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparişOtomasyon.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEslesmelerle
    {
        public string Vkn { get; set; }
        public string MusteriID { get; set; }
        public string Unvan { get; set; }
        public string AdresID { get; set; }
        public string AdresAdi { get; set; }
        public string İl { get; set; }
        public string İlce { get; set; }
        public string Adko { get; set; }
        public string Apak { get; set; }
        public string Reka { get; set; }
        public string TekirdagUn { get; set; }
        public string Sudesan { get; set; }
        public int ID { get; set; }
        public string Milhans { get; set; }
        public string Dogtas { get; set; }
        public string Gezer { get; set; }
        public string EsGlobal { get; set; }
        public string MutluMakarna { get; set; }
        public string Saruhan { get; set; }
        public string KucukBay { get; set; }
        public string Bunge { get; set; }
        public string Hedef { get; set; }
    }
}
