//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparişOtomasyon.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGezer
    {
        public int ID { get; set; }
        public string Vkn { get; set; }
        public string AdresID { get; set; }
        public string Unvan { get; set; }
        public string AdresAdi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string AdresIlVeIlce { get; set; }
        public string Adres { get; set; }
        public string MusteridenGelen { get; set; }
    }
}
