//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparişOtomasyon.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGezerProjeler
    {
        public int ID { get; set; }
        public string projelerID { get; set; }
        public string FaturaFirmasıUnvanı { get; set; }
        public string Proje { get; set; }
        public string Hizmet { get; set; }
        public string Vade { get; set; }
    }
}
